#
# The default service configuration
#

coordinator:
  # address if the server want to connect directly to debug
  debugHost:
  # enable ROM library monitoring
  libMonitor: false
  monitoring:
    port: 6601
    profiler: false
    metric: false
    urlPrefix: /coordinator
  # the public domain of the coordinator
  publicDomain: http://localhost:8000
  # specify the worker address that the client can ping (with protocol and port)
  pingServer:

worker:
  network:
    coordinatorAddress: localhost:8000
    httpPort: 9000
    port: 8800
    zone:
  monitoring:
    # monitoring server port
    port: 6601
    profiler: false
    # monitoring server URL prefix
    metric: true
    urlPrefix: /worker

shared:
  server:
    port: 8000
    httpsPort: 9999
    httpsKey:
    httpsChain:

emulator:
  # set output viewport scale factor
  scale: 1

  # enable aspect ratio changing
  # (experimental)
  aspectRatio:
    keep: false
    # recalculate emulator game frame size to the given WxH
    width: 320
    height: 240

  # !to check proper params for changing

  libretro:
    cores:
      paths:
        libs: assets/emulator/libretro/cores
        configs: assets/emulator/libretro/cores
      # Libretro core configuration
      #
      # Available config params:
      #   - lib (string)
      #   - config (string)
      #   - roms ([]string)
      #   - width (int)
      #   - height (int)
      #   - ratio (float)
      #   - isGlAllowed (bool)
      #   - usesLibCo (bool)
      #   - hasMultitap (bool)
      list:
        gba:
          lib: mgba_libretro
          roms: [ "gba", "gbc" ]
          width: 240
          height: 160
        pcsx:
          lib: pcsx_rearmed_libretro
          roms: [ "cue" ]
          width: 350
          height: 240
        nes:
          lib: nestopia_libretro
          roms: [ "nes" ]
          width: 256
          height: 240
        snes:
          lib: snes9x_libretro
          roms: [ "smc", "sfc", "swc", "fig", "bs" ]
          width: 256
          height: 224
          hasMultitap: true
        mame:
          lib: fbneo_libretro
          roms: [ "zip" ]
          width: 240
          height: 160
        n64:
          lib: mupen64plus_next_libretro
          config: mupen64plus_next_libretro.cfg
          roms: [ "n64", "v64", "z64" ]
          width: 320
          height: 240
          isGlAllowed: true
          usesLibCo: true

encoder:
  # run without a game
  # (experimental)
  withoutGame: false

webrtc:
  iceServers:
    - url: stun:stun.l.google.com:19302
    - url: stun:{server-ip}:3478
    - url: turn:{server-ip}:3478
      username: root
      credential: root
